import { Router } from "express";
import { authRouter } from "./auth";
import { uploadRouter } from "./upload";
import { userRouter } from "./user";
import { collectionRouter } from "./collection";
import { seasonRouter } from "./season";
import { scentRouter } from "./scent";
import { settingsRouter } from "./settings";
import { bannerRouter } from "./banner";
import { topbarRouter } from "./topbar";
import { instagramRouter } from "./instagram";
import { productRouter } from "./product";
import { ratingRouter } from "./rating";
import { phonepeRouter } from "./phonepe";
import { returnExchangeRouter } from "./returnexchange";
import { privacyPolicyRouter } from "./privacypolicy";
import { termsConditionsRouter } from "./termsconditions";
import { refundPolicyRouter } from "./refundpolicy";
import { termsServiceRouter } from "./termsservice";
import { contactUsRouter } from "./contactus";
import { newsletterRouter } from "./newsletter";
import { blogRouter } from "./blog";

const router = Router();

router.use("/auth", authRouter);
router.use("/upload", uploadRouter);
router.use("/user", userRouter);
router.use("/collection", collectionRouter);
router.use("/season", seasonRouter);
router.use("/scent", scentRouter);
router.use("/settings", settingsRouter);
router.use("/banner", bannerRouter);
router.use("/topbar", topbarRouter);
router.use("/instagram", instagramRouter);
router.use("/product", productRouter);
router.use("/rating", ratingRouter);
router.use("/phonepe", phonepeRouter);
router.use("/return-exchange", returnExchangeRouter);
router.use("/privacy-policy", privacyPolicyRouter);
router.use("/terms-conditions", termsConditionsRouter);
router.use("/refund-policy", refundPolicyRouter);
router.use("/terms-of-service", termsServiceRouter);
router.use("/contact-us", contactUsRouter);
router.use("/newsletter", newsletterRouter);
router.use("/blog", blogRouter);

export { router };
